version: "3"

services: 

  cache: 
    image: redis
    ports:
      - 6379:6379
    container_name: cache
    networks:
      - tracker


  database:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    networks:
      - tracker

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://database:27017/
    networks:
      - tracker



networks:
  tracker:
    driver: bridge